[#apidoc-audit]
= audit


== Available methods

* <<apidoc-audit-listImagesByPatchStatus,listImagesByPatchStatus>>
* <<apidoc-audit-listImagesByPatchStatus,listImagesByPatchStatus>>
* <<apidoc-audit-listSystemsByPatchStatus,listSystemsByPatchStatus>>
* <<apidoc-audit-listSystemsByPatchStatus,listSystemsByPatchStatus>>

== Description

Methods to audit systems.

*Namespace*:

audit

'''


[#apidoc-audit-listImagesByPatchStatus]
== Method: listImagesByPatchStatus 

Description:

List visible images with their patch status regarding a given CVE
 identifier. Please note that the query code relies on data that is pre-generated
 by the 'cve-server-channels' taskomatic job.




Parameters:

  * [.string]#string#  sessionKey
 
* [.string]#string#  cveIdentifier
 

Returns:

* [.array]#array# :
 * [.struct]#struct#  - cve_audit_image
     * [.int]#int#  "image_id"
     * [.string]#string#  "patch_status"
         // no end needed
             * AFFECTED_PATCH_INAPPLICABLE - Affected, patch available in unassigned channel
             * AFFECTED_PATCH_APPLICABLE - Affected, patch available in assigned channel
             * NOT_AFFECTED - Not affected
             * PATCHED - Patched
         // no end needed
     * [.array]#array#  "string"
** channel_labels - Labels of channels that contain an unapplied patch
     * [.array]#array#  "string"
** errata_advisories - Advisories of erratas that patch the specified vulnerability
 // no end needed
  // no end needed
 


'''


[#apidoc-audit-listImagesByPatchStatus]
== Method: listImagesByPatchStatus 

Description:

List visible images with their patch status regarding a given CVE
 identifier. Filter the results by passing in a list of patch status labels.
 Please note that the query code relies on data that is pre-generated by the
 'cve-server-channels' taskomatic job.




Parameters:

  * [.string]#string#  sessionKey
 
* [.string]#string#  cveIdentifier
 
* [.array]#array# :
** string - patchStatusLabel
  // no end needed
      * AFFECTED_PATCH_INAPPLICABLE - Affected, patch available in unassigned channel
      * AFFECTED_PATCH_APPLICABLE - Affected, patch available in assigned channel
      * NOT_AFFECTED - Not affected
      * PATCHED - Patched
  // no end needed
 

Returns:

* [.array]#array# :
 * [.struct]#struct#  - cve_audit_image
     * [.int]#int#  "image_id"
     * [.string]#string#  "patch_status"
         // no end needed
             * AFFECTED_PATCH_INAPPLICABLE - Affected, patch available in unassigned channel
             * AFFECTED_PATCH_APPLICABLE - Affected, patch available in assigned channel
             * NOT_AFFECTED - Not affected
             * PATCHED - Patched
         // no end needed
     * [.array]#array#  "string"
** channel_labels - Labels of channels that contain an unapplied patch
     * [.array]#array#  "string"
** errata_advisories - Advisories of erratas that patch the specified vulnerability
 // no end needed
  // no end needed
 


'''


[#apidoc-audit-listSystemsByPatchStatus]
== Method: listSystemsByPatchStatus 

Description:

List visible systems with their patch status regarding a given CVE
 identifier. Please note that the query code relies on data that is pre-generated
 by the 'cve-server-channels' taskomatic job.




Parameters:

  * [.string]#string#  sessionKey
 
* [.string]#string#  cveIdentifier
 

Returns:

* [.array]#array# :
 * [.struct]#struct#  - cve_audit_system
     * [.int]#int#  "system_id"
     * [.string]#string#  "patch_status"
         // no end needed
             * AFFECTED_PATCH_INAPPLICABLE - Affected, patch available in unassigned channel
             * AFFECTED_PATCH_APPLICABLE - Affected, patch available in assigned channel
             * NOT_AFFECTED - Not affected
             * PATCHED - Patched
         // no end needed
     * [.array]#array#  "string"
** channel_labels - Labels of channels that contain an unapplied patch
     * [.array]#array#  "string"
** errata_advisories - Advisories of erratas that patch the specified vulnerability
 // no end needed
  // no end needed
 


'''


[#apidoc-audit-listSystemsByPatchStatus]
== Method: listSystemsByPatchStatus 

Description:

List visible systems with their patch status regarding a given CVE
 identifier. Filter the results by passing in a list of patch status labels.
 Please note that the query code relies on data that is pre-generated by the
 'cve-server-channels' taskomatic job.




Parameters:

  * [.string]#string#  sessionKey
 
* [.string]#string#  cveIdentifier
 
* [.array]#array# :
** string - patchStatusLabel
  // no end needed
      * AFFECTED_PATCH_INAPPLICABLE - Affected, patch available in unassigned channel
      * AFFECTED_PATCH_APPLICABLE - Affected, patch available in assigned channel
      * NOT_AFFECTED - Not affected
      * PATCHED - Patched
  // no end needed
 

Returns:

* [.array]#array# :
 * [.struct]#struct#  - cve_audit_system
     * [.int]#int#  "system_id"
     * [.string]#string#  "patch_status"
         // no end needed
             * AFFECTED_PATCH_INAPPLICABLE - Affected, patch available in unassigned channel
             * AFFECTED_PATCH_APPLICABLE - Affected, patch available in assigned channel
             * NOT_AFFECTED - Not affected
             * PATCHED - Patched
         // no end needed
     * [.array]#array#  "string"
** channel_labels - Labels of channels that contain an unapplied patch
     * [.array]#array#  "string"
** errata_advisories - Advisories of erratas that patch the specified vulnerability
 // no end needed
  // no end needed
 


'''

