[#apidoc-audit]
= audit


== Available methods

* <<apidoc-audit-listImagesByPatchStatus-879042661,listImagesByPatchStatus>>
* <<apidoc-audit-listImagesByPatchStatus-1035726142,listImagesByPatchStatus>>
* <<apidoc-audit-listSystemsByPatchStatus-763937215,listSystemsByPatchStatus>>
* <<apidoc-audit-listSystemsByPatchStatus-909570727,listSystemsByPatchStatus>>

== Description

Methods to audit systems.

*Namespace*:

audit


[#apidoc-audit-listImagesByPatchStatus-879042661]
== Method: listImagesByPatchStatus

HTTP `GET`

Description:

List visible images with their patch status regarding a given CVE
 identifier. Please note that the query code relies on data that is pre-generated
 by the 'cve-server-channels' taskomatic job.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  cveIdentifier
 

Returns:

* [.array]#array# :
 * [.struct]#struct#  CVE audit image
** [.int]#int#  "image_id"
** [.string]#string#  "patch_status"
*** AFFECTED_PATCH_INAPPLICABLE - affected, patch available in unassigned channel
*** AFFECTED_PATCH_APPLICABLE - affected, patch available in assigned channel
*** NOT_AFFECTED - not affected
*** PATCHED - patched
** [.array]#channel_labels array#  "string" - labels of channels that contain an unapplied patch
** [.array]#errata_advisories array#  "string" - advisories of erratas that patch the specified vulnerability
   
 



[#apidoc-audit-listImagesByPatchStatus-1035726142]
== Method: listImagesByPatchStatus

HTTP `GET`

Description:

List visible images with their patch status regarding a given CVE
 identifier. Filter the results by passing in a list of patch status labels.
 Please note that the query code relies on data that is pre-generated by the
 'cve-server-channels' taskomatic job.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  cveIdentifier
 
* [.array]#string array#  patchStatusLabels
** AFFECTED_PATCH_INAPPLICABLE - Affected, patch available in unassigned channel
** AFFECTED_PATCH_APPLICABLE - Affected, patch available in assigned channel
** NOT_AFFECTED - Not affected
** PATCHED - Patched
 

Returns:

* [.array]#array# :
 * [.struct]#struct#  CVE audit image
** [.int]#int#  "image_id"
** [.string]#string#  "patch_status"
*** AFFECTED_PATCH_INAPPLICABLE - affected, patch available in unassigned channel
*** AFFECTED_PATCH_APPLICABLE - affected, patch available in assigned channel
*** NOT_AFFECTED - not affected
*** PATCHED - patched
** [.array]#channel_labels array#  "string" - labels of channels that contain an unapplied patch
** [.array]#errata_advisories array#  "string" - advisories of erratas that patch the specified vulnerability
   
 



[#apidoc-audit-listSystemsByPatchStatus-763937215]
== Method: listSystemsByPatchStatus

HTTP `GET`

Description:

List visible systems with their patch status regarding a given CVE
 identifier. Please note that the query code relies on data that is pre-generated
 by the 'cve-server-channels' taskomatic job.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  cveIdentifier
 

Returns:

* [.array]#array# :
 * [.struct]#struct#  CVE audit system
** [.int]#int#  "system_id"
** [.string]#string#  "patch_status"
*** AFFECTED_PATCH_INAPPLICABLE - affected, patch available in unassigned channel
*** AFFECTED_PATCH_APPLICABLE - affected, patch available in assigned channel
*** NOT_AFFECTED - not affected
*** PATCHED - patched
** [.array]#channel_labels array#  "string" - labels of channels that contain an unapplied patch
** [.array]#errata_advisories array#  "string" - advisories of erratas that patch the specified vulnerability
   
 



[#apidoc-audit-listSystemsByPatchStatus-909570727]
== Method: listSystemsByPatchStatus

HTTP `GET`

Description:

List visible systems with their patch status regarding a given CVE
 identifier. Filter the results by passing in a list of patch status labels.
 Please note that the query code relies on data that is pre-generated by the
 'cve-server-channels' taskomatic job.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  cveIdentifier
 
* [.array]#string array#  patchStatusLabels
** AFFECTED_PATCH_INAPPLICABLE - Affected, patch available in unassigned channel
** AFFECTED_PATCH_APPLICABLE - Affected, patch available in assigned channel
** NOT_AFFECTED - Not affected
** PATCHED - Patched
 

Returns:

* [.array]#array# :
 * [.struct]#struct#  CVE audit system
** [.int]#int#  "system_id"
** [.string]#string#  "patch_status"
*** AFFECTED_PATCH_INAPPLICABLE - affected, patch available in unassigned channel
*** AFFECTED_PATCH_APPLICABLE - affected, patch available in assigned channel
*** NOT_AFFECTED - not affected
*** PATCHED - patched
** [.array]#channel_labels array#  "string" - labels of channels that contain an unapplied patch
** [.array]#errata_advisories array#  "string" - advisories of erratas that patch the specified vulnerability
   
 


