[#apidoc-channel_access]
= channel.access


== Available methods

* <<apidoc-channel_access-disableUserRestrictions-loggedInUser-channelLabel,disableUserRestrictions>>
* <<apidoc-channel_access-enableUserRestrictions-loggedInUser-channelLabel,enableUserRestrictions>>
* <<apidoc-channel_access-getOrgSharing-loggedInUser-channelLabel,getOrgSharing>>
* <<apidoc-channel_access-setOrgSharing-loggedInUser-channelLabel-access,setOrgSharing>>

== Description

Provides methods to retrieve and alter channel access restrictions.

*Namespace*:

channel.access


[#apidoc-channel_access-disableUserRestrictions-loggedInUser-channelLabel]
== Method: disableUserRestrictions

HTTP `POST`

Description:

Disable user restrictions for the given channel.  If disabled,
 all users within the organization may subscribe to the channel.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  channelLabel - label of the channel
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-channel_access-enableUserRestrictions-loggedInUser-channelLabel]
== Method: enableUserRestrictions

HTTP `POST`

Description:

Enable user restrictions for the given channel. If enabled, only
 selected users within the organization may subscribe to the channel.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  channelLabel - label of the channel
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-channel_access-getOrgSharing-loggedInUser-channelLabel]
== Method: getOrgSharing

HTTP `GET`

Description:

Get organization sharing access control.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  channelLabel - label of the channel
 

Returns:

* [.string]#string#  access - The access value (one of the following: 'public', 'private', or 'protected'
 



[#apidoc-channel_access-setOrgSharing-loggedInUser-channelLabel-access]
== Method: setOrgSharing

HTTP `POST`

Description:

Set organization sharing access control.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  channelLabel - label of the channel
 
* [.string]#string#  access - Access (one of the
                  following: 'public', 'private', or 'protected'
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 


