[#apidoc-org]
= org


== Available methods

* <<apidoc-org-create-182834500,create>>
* <<apidoc-org-createFirst-1475804169,createFirst>>
* <<apidoc-org-delete-347701627,delete>>
* <<apidoc-org-getClmSyncPatchesConfig-626754729,getClmSyncPatchesConfig>>
* <<apidoc-org-getDetails-126142286,getDetails>>
* <<apidoc-org-getDetails-1609448604,getDetails>>
* <<apidoc-org-getPolicyForScapFileUpload-1543420346,getPolicyForScapFileUpload>>
* <<apidoc-org-getPolicyForScapResultDeletion-40245733,getPolicyForScapResultDeletion>>
* <<apidoc-org-isContentStagingEnabled-807771233,isContentStagingEnabled>>
* <<apidoc-org-isErrataEmailNotifsForOrg-641078642,isErrataEmailNotifsForOrg>>
* <<apidoc-org-isOrgConfigManagedByOrgAdmin-1782724863,isOrgConfigManagedByOrgAdmin>>
* <<apidoc-org-listOrgs-1959734623,listOrgs>>
* <<apidoc-org-listUsers-170698369,listUsers>>
* <<apidoc-org-migrateSystems-817880261,migrateSystems>>
* <<apidoc-org-setClmSyncPatchesConfig-975724693,setClmSyncPatchesConfig>>
* <<apidoc-org-setContentStaging-869304868,setContentStaging>>
* <<apidoc-org-setErrataEmailNotifsForOrg-1573405835,setErrataEmailNotifsForOrg>>
* <<apidoc-org-setOrgConfigManagedByOrgAdmin-731431696,setOrgConfigManagedByOrgAdmin>>
* <<apidoc-org-setPolicyForScapFileUpload-1290911050,setPolicyForScapFileUpload>>
* <<apidoc-org-setPolicyForScapResultDeletion-1147103911,setPolicyForScapResultDeletion>>
* <<apidoc-org-transferSystems-513477778,transferSystems>>
* <<apidoc-org-updateName-2119663341,updateName>>

== Description

Contains methods to access common organization management
 functions available from the web interface.

*Namespace*:

org


[#apidoc-org-create-182834500]
== Method: create

HTTP `POST`

Description:

Create a new organization and associated administrator account.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  orgName - Organization name. Must meet same
 criteria as in the web UI.
 
* [.string]#string#  adminLogin - New administrator login name.
 
* [.string]#string#  adminPassword - New administrator password.
 
* [.string]#string#  prefix - New administrator's prefix. Must
 match one of the values available in the web UI. (i.e. Dr., Mr., Mrs., Sr., etc.)
 
* [.string]#string#  firstName - New administrator's first name.
 
* [.string]#string#  lastName - New administrator's first name.
 
* [.string]#string#  email - New administrator's e-mail.
 
* [.boolean]#boolean#  usePamAuth - True if PAM authentication
 should be used for the new administrator account.
 

Returns:

* * [.struct]#struct#  organization info
** [.int]#int#  "id"
** [.string]#string#  "name"
** [.int]#int#  "active_users" - number of active users in the organization
** [.int]#int#  "systems" - number of systems in the organization
** [.int]#int#  "trusts" - number of trusted organizations
** [.int]#int#  "system_groups" - number of system groups in the organization (optional)
** [.int]#int#  "activation_keys" - number of activation keys in the organization (optional)
** [.int]#int#  "kickstart_profiles" - number of kickstart profiles in the organization (optional)
** [.int]#int#  "configuration_channels" - number of configuration channels in the organization (optional)
** [.boolean]#boolean#  "staging_content_enabled" - is staging content enabled in organization (optional)
  
 



[#apidoc-org-createFirst-1475804169]
== Method: createFirst

HTTP `POST`

Description:

Create first organization and user after initial setup without authentication




Parameters:

* [.string]#string#  orgName - Organization name. Must meet same
 criteria as in the web UI.
 
* [.string]#string#  adminLogin - New administrator login name.
 
* [.string]#string#  adminPassword - New administrator password.
 
* [.string]#string#  firstName - New administrator's first name.
 
* [.string]#string#  lastName - New administrator's first name.
 
* [.string]#string#  email - New administrator's e-mail.
 

Returns:

* * [.struct]#struct#  organization info
** [.int]#int#  "id"
** [.string]#string#  "name"
** [.int]#int#  "active_users" - number of active users in the organization
** [.int]#int#  "systems" - number of systems in the organization
** [.int]#int#  "trusts" - number of trusted organizations
** [.int]#int#  "system_groups" - number of system groups in the organization (optional)
** [.int]#int#  "activation_keys" - number of activation keys in the organization (optional)
** [.int]#int#  "kickstart_profiles" - number of kickstart profiles in the organization (optional)
** [.int]#int#  "configuration_channels" - number of configuration channels in the organization (optional)
** [.boolean]#boolean#  "staging_content_enabled" - is staging content enabled in organization (optional)
  
 



[#apidoc-org-delete-347701627]
== Method: delete

HTTP `POST`

Description:

Delete an organization. The default organization
 (i.e. orgId=1) cannot be deleted.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-getClmSyncPatchesConfig-626754729]
== Method: getClmSyncPatchesConfig

HTTP `GET`

Description:

Reads the content lifecycle management patch synchronization config option.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.boolean]#boolean#  status - Get the config option value
 



[#apidoc-org-getDetails-126142286]
== Method: getDetails

HTTP `GET`

Description:

The detailed information about an organization given
 the organization ID.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* * [.struct]#struct#  organization info
** [.int]#int#  "id"
** [.string]#string#  "name"
** [.int]#int#  "active_users" - number of active users in the organization
** [.int]#int#  "systems" - number of systems in the organization
** [.int]#int#  "trusts" - number of trusted organizations
** [.int]#int#  "system_groups" - number of system groups in the organization (optional)
** [.int]#int#  "activation_keys" - number of activation keys in the organization (optional)
** [.int]#int#  "kickstart_profiles" - number of kickstart profiles in the organization (optional)
** [.int]#int#  "configuration_channels" - number of configuration channels in the organization (optional)
** [.boolean]#boolean#  "staging_content_enabled" - is staging content enabled in organization (optional)
  
 



[#apidoc-org-getDetails-1609448604]
== Method: getDetails

HTTP `GET`

Description:

The detailed information about an organization given
 the organization name.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name
 

Returns:

* * [.struct]#struct#  organization info
** [.int]#int#  "id"
** [.string]#string#  "name"
** [.int]#int#  "active_users" - number of active users in the organization
** [.int]#int#  "systems" - number of systems in the organization
** [.int]#int#  "trusts" - number of trusted organizations
** [.int]#int#  "system_groups" - number of system groups in the organization (optional)
** [.int]#int#  "activation_keys" - number of activation keys in the organization (optional)
** [.int]#int#  "kickstart_profiles" - number of kickstart profiles in the organization (optional)
** [.int]#int#  "configuration_channels" - number of configuration channels in the organization (optional)
** [.boolean]#boolean#  "staging_content_enabled" - is staging content enabled in organization (optional)
  
 



[#apidoc-org-getPolicyForScapFileUpload-1543420346]
== Method: getPolicyForScapFileUpload

HTTP `GET`

Description:

Get the status of SCAP detailed result file upload settings
 for the given organization.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.struct]#struct#  scap_upload_info
** [.boolean]#boolean#  "enabled" - Aggregation of detailed SCAP results is enabled.
** [.int]#int#  "size_limit" - Limit (in Bytes) for a single SCAP file upload.
 



[#apidoc-org-getPolicyForScapResultDeletion-40245733]
== Method: getPolicyForScapResultDeletion

HTTP `GET`

Description:

Get the status of SCAP result deletion settings for the given
 organization.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.struct]#struct#  scap_deletion_info
** [.boolean]#boolean#  "enabled" - Deletion of SCAP results is enabled
** [.int]#int#  "retention_period" - Period (in days) after which a scan can be deleted (if enabled).
 



[#apidoc-org-isContentStagingEnabled-807771233]
== Method: isContentStagingEnabled

HTTP `GET`

Description:

Get the status of content staging settings for the given organization.
 Returns true if enabled, false otherwise.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.boolean]#boolean#  status - Get the status of content staging settings
 



[#apidoc-org-isErrataEmailNotifsForOrg-641078642]
== Method: isErrataEmailNotifsForOrg

HTTP `GET`

Description:

Returns whether errata e-mail notifications are enabled
 for the organization




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.boolean]#boolean#  status - Returns the status of the errata e-mail notification
 setting for the organization
 



[#apidoc-org-isOrgConfigManagedByOrgAdmin-1782724863]
== Method: isOrgConfigManagedByOrgAdmin

HTTP `GET`

Description:

Returns whether Organization Administrator is able to manage his
 organization configuration. This may have a high impact on general #product() performance.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.boolean]#boolean#  status - Returns the status org admin management setting
 



[#apidoc-org-listOrgs-1959734623]
== Method: listOrgs

HTTP `GET`

Description:

Returns the list of organizations.




Parameters:

* [.string]#string#  sessionKey
 

Returns:

* [.array]#array# :
     * [.struct]#struct#  organization info
** [.int]#int#  "id"
** [.string]#string#  "name"
** [.int]#int#  "active_users" - number of active users in the organization
** [.int]#int#  "systems" - number of systems in the organization
** [.int]#int#  "trusts" - number of trusted organizations
** [.int]#int#  "system_groups" - number of system groups in the organization (optional)
** [.int]#int#  "activation_keys" - number of activation keys in the organization (optional)
** [.int]#int#  "kickstart_profiles" - number of kickstart profiles in the organization (optional)
** [.int]#int#  "configuration_channels" - number of configuration channels in the organization (optional)
** [.boolean]#boolean#  "staging_content_enabled" - is staging content enabled in organization (optional)
 
 



[#apidoc-org-listUsers-170698369]
== Method: listUsers

HTTP `GET`

Description:

Returns the list of users in a given organization.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.array]#array# :
     * [.struct]#struct#  user
** [.string]#string#  "login"
** [.string]#string#  "login_uc"
** [.string]#string#  "name"
** [.string]#string#  "email"
** [.boolean]#boolean#  "is_org_admin"
 
 



[#apidoc-org-migrateSystems-817880261]
== Method: migrateSystems (Deprecated)

HTTP `POST`

Description:

Transfer systems from one organization to another.  If executed by
 a #product() administrator, the systems will be transferred from their current
 organization to the organization specified by the toOrgId.  If executed by
 an organization administrator, the systems must exist in the same organization
 as that administrator and the systems will be transferred to the organization
 specified by the toOrgId. In any scenario, the origination and destination
 organizations must be defined in a trust.

 Note: This method is deprecated and will be removed in a future API version. Please use
 transferSystems instead.


Deprecated - being replaced by org.transferSystems(User loggedInUser, Integer toOrgId,
 List(Integer) sids)


Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  toOrgId - ID of the organization where the
 system(s) will be transferred to.
 
* [.array]#int array#  sids
 

Returns:

* [.array]#int array#  serverIdTransferred
 



[#apidoc-org-setClmSyncPatchesConfig-975724693]
== Method: setClmSyncPatchesConfig

HTTP `POST`

Description:

Sets the content lifecycle management patch synchronization config option.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.boolean]#boolean#  value - The config option value
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setContentStaging-869304868]
== Method: setContentStaging

HTTP `POST`

Description:

Set the status of content staging for the given organization.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.boolean]#boolean#  enable - Use true/false to enable/disable
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setErrataEmailNotifsForOrg-1573405835]
== Method: setErrataEmailNotifsForOrg

HTTP `POST`

Description:

Dis/enables errata e-mail notifications for the organization




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.boolean]#boolean#  enable - Use true/false to enable/disable
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setOrgConfigManagedByOrgAdmin-731431696]
== Method: setOrgConfigManagedByOrgAdmin

HTTP `POST`

Description:

Sets whether Organization Administrator can manage his organization
 configuration. This may have a high impact on general #product() performance.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.boolean]#boolean#  enable - Use true/false to enable/disable
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setPolicyForScapFileUpload-1290911050]
== Method: setPolicyForScapFileUpload

HTTP `POST`

Description:

Set the status of SCAP detailed result file upload settings
 for the given organization.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.struct]#struct#  newSettings
** [.boolean]#boolean#  "enabled" - Aggregation of detailed SCAP results is enabled.
** [.int]#int#  "size_limit" - Limit (in Bytes) for a single SCAP file upload.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setPolicyForScapResultDeletion-1147103911]
== Method: setPolicyForScapResultDeletion

HTTP `POST`

Description:

Set the status of SCAP result deletion settins for the given
 organization.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.struct]#struct#  newSettings
** [.boolean]#boolean#  "enabled" - Deletion of SCAP results is enabled
** [.int]#int#  "retention_period" - Period (in days) after which a scan can be deleted (if enabled).
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-transferSystems-513477778]
== Method: transferSystems

HTTP `POST`

Description:

Transfer systems from one organization to another.  If executed by
 a #product() administrator, the systems will be transferred from their current
 organization to the organization specified by the toOrgId.  If executed by
 an organization administrator, the systems must exist in the same organization
 as that administrator and the systems will be transferred to the organization
 specified by the toOrgId. In any scenario, the origination and destination
 organizations must be defined in a trust.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  toOrgId - ID of the organization where the
 system(s) will be transferred to.
 
* [.array]#int array#  sids
 

Returns:

* [.array]#int array#  serverIdTransferred
 



[#apidoc-org-updateName-2119663341]
== Method: updateName

HTTP `POST`

Description:

Updates the name of an organization




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.string]#string#  name - Organization name. Must meet same
 criteria as in the web UI.
 

Returns:

* * [.struct]#struct#  organization info
** [.int]#int#  "id"
** [.string]#string#  "name"
** [.int]#int#  "active_users" - number of active users in the organization
** [.int]#int#  "systems" - number of systems in the organization
** [.int]#int#  "trusts" - number of trusted organizations
** [.int]#int#  "system_groups" - number of system groups in the organization (optional)
** [.int]#int#  "activation_keys" - number of activation keys in the organization (optional)
** [.int]#int#  "kickstart_profiles" - number of kickstart profiles in the organization (optional)
** [.int]#int#  "configuration_channels" - number of configuration channels in the organization (optional)
** [.boolean]#boolean#  "staging_content_enabled" - is staging content enabled in organization (optional)
  
 


