[#apidoc-org]
= org


== Available methods

* <<apidoc-org-create-1747223278,create>>
* <<apidoc-org-delete-739905410,delete>>
* <<apidoc-org-getClmSyncPatchesConfig-1128933904,getClmSyncPatchesConfig>>
* <<apidoc-org-getDetails-854246299,getDetails>>
* <<apidoc-org-getDetails-1324399707,getDetails>>
* <<apidoc-org-getPolicyForScapFileUpload-1438317505,getPolicyForScapFileUpload>>
* <<apidoc-org-getPolicyForScapResultDeletion-651177414,getPolicyForScapResultDeletion>>
* <<apidoc-org-isContentStagingEnabled-1749988512,isContentStagingEnabled>>
* <<apidoc-org-isErrataEmailNotifsForOrg-1605410974,isErrataEmailNotifsForOrg>>
* <<apidoc-org-isOrgConfigManagedByOrgAdmin-649154765,isOrgConfigManagedByOrgAdmin>>
* <<apidoc-org-listOrgs-391595516,listOrgs>>
* <<apidoc-org-listUsers-524225829,listUsers>>
* <<apidoc-org-migrateSystems-52439501,migrateSystems>>
* <<apidoc-org-setClmSyncPatchesConfig-1844179384,setClmSyncPatchesConfig>>
* <<apidoc-org-setContentStaging-430231018,setContentStaging>>
* <<apidoc-org-setErrataEmailNotifsForOrg-1932244125,setErrataEmailNotifsForOrg>>
* <<apidoc-org-setOrgConfigManagedByOrgAdmin-1660891176,setOrgConfigManagedByOrgAdmin>>
* <<apidoc-org-setPolicyForScapFileUpload-616302301,setPolicyForScapFileUpload>>
* <<apidoc-org-setPolicyForScapResultDeletion-618120037,setPolicyForScapResultDeletion>>
* <<apidoc-org-transferSystems-1224302486,transferSystems>>
* <<apidoc-org-updateName-8633259,updateName>>

== Description

Contains methods to access common organization management
 functions available from the web interface.

*Namespace*:

org


[#apidoc-org-create-1747223278]
== Method: create 

Description:

Create a new organization and associated administrator account.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  orgName - Organization name. Must meet same
 criteria as in the web UI.
 
* [.string]#string#  adminLogin - New administrator login name.
 
* [.string]#string#  adminPassword - New administrator password.
 
* [.string]#string#  prefix - New administrator's prefix. Must
 match one of the values available in the web UI. (i.e. Dr., Mr., Mrs., Sr., etc.)
 
* [.string]#string#  firstName - New administrator's first name.
 
* [.string]#string#  lastName - New administrator's first name.
 
* [.string]#string#  email - New administrator's e-mail.
 
* [.boolean]#boolean#  usePamAuth - True if PAM authentication
 should be used for the new administrator account.
 

Returns:

* * [.struct]#struct#  - organization info
   ** [.int]#int#  "id"
   ** [.string]#string#  "name"
   ** [.int]#int#  "active_users" - Number of active users in the organization.
   ** [.int]#int#  "systems" - Number of systems in the organization.
   ** [.int]#int#  "trusts" - Number of trusted organizations.
   ** [.int]#int#  "system_groups" - Number of system groups in the organization. (optional)
   ** [.int]#int#  "activation_keys" - Number of activation keys in the organization. (optional)
   ** [.int]#int#  "kickstart_profiles" - Number of kickstart profiles in the organization. (optional)
   ** [.int]#int#  "configuration_channels" - Number of configuration channels in the organization. (optional)
   ** [.boolean]#boolean#  "staging_content_enabled" - Is staging content enabled in organization. (optional)
   
 



[#apidoc-org-delete-739905410]
== Method: delete 

Description:

Delete an organization. The default organization
 (i.e. orgId=1) cannot be deleted.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-getClmSyncPatchesConfig-1128933904]
== Method: getClmSyncPatchesConfig 

Description:

Reads the content lifecycle management patch synchronization config option.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.boolean]#boolean#  status - Get the config option value
 



[#apidoc-org-getDetails-854246299]
== Method: getDetails 

Description:

The detailed information about an organization given
 the organization ID.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* * [.struct]#struct#  - organization info
   ** [.int]#int#  "id"
   ** [.string]#string#  "name"
   ** [.int]#int#  "active_users" - Number of active users in the organization.
   ** [.int]#int#  "systems" - Number of systems in the organization.
   ** [.int]#int#  "trusts" - Number of trusted organizations.
   ** [.int]#int#  "system_groups" - Number of system groups in the organization. (optional)
   ** [.int]#int#  "activation_keys" - Number of activation keys in the organization. (optional)
   ** [.int]#int#  "kickstart_profiles" - Number of kickstart profiles in the organization. (optional)
   ** [.int]#int#  "configuration_channels" - Number of configuration channels in the organization. (optional)
   ** [.boolean]#boolean#  "staging_content_enabled" - Is staging content enabled in organization. (optional)
   
 



[#apidoc-org-getDetails-1324399707]
== Method: getDetails 

Description:

The detailed information about an organization given
 the organization name.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name
 

Returns:

* * [.struct]#struct#  - organization info
   ** [.int]#int#  "id"
   ** [.string]#string#  "name"
   ** [.int]#int#  "active_users" - Number of active users in the organization.
   ** [.int]#int#  "systems" - Number of systems in the organization.
   ** [.int]#int#  "trusts" - Number of trusted organizations.
   ** [.int]#int#  "system_groups" - Number of system groups in the organization. (optional)
   ** [.int]#int#  "activation_keys" - Number of activation keys in the organization. (optional)
   ** [.int]#int#  "kickstart_profiles" - Number of kickstart profiles in the organization. (optional)
   ** [.int]#int#  "configuration_channels" - Number of configuration channels in the organization. (optional)
   ** [.boolean]#boolean#  "staging_content_enabled" - Is staging content enabled in organization. (optional)
   
 



[#apidoc-org-getPolicyForScapFileUpload-1438317505]
== Method: getPolicyForScapFileUpload 

Description:

Get the status of SCAP detailed result file upload settings
 for the given organization.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.struct]#struct#  - scap_upload_info
         ** [.boolean]#boolean#  "enabled" - Aggregation of detailed SCAP results is enabled.
         ** [.int]#int#  "size_limit" - Limit (in Bytes) for a single SCAP file upload.
      



[#apidoc-org-getPolicyForScapResultDeletion-651177414]
== Method: getPolicyForScapResultDeletion 

Description:

Get the status of SCAP result deletion settings for the given
 organization.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.struct]#struct#  - scap_deletion_info
         ** [.boolean]#boolean#  "enabled" - Deletion of SCAP results is enabled
         ** [.int]#int#  "retention_period" - Period (in days) after which a scan can be deleted (if enabled).
      



[#apidoc-org-isContentStagingEnabled-1749988512]
== Method: isContentStagingEnabled 

Description:

Get the status of content staging settings for the given organization.
 Returns true if enabled, false otherwise.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.boolean]#boolean#  status - Get the status of content staging settings
 



[#apidoc-org-isErrataEmailNotifsForOrg-1605410974]
== Method: isErrataEmailNotifsForOrg 

Description:

Returns whether errata e-mail notifications are enabled
 for the organization




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.boolean]#boolean#  status - Returns the status of the errata e-mail notification
 setting for the organization
 



[#apidoc-org-isOrgConfigManagedByOrgAdmin-649154765]
== Method: isOrgConfigManagedByOrgAdmin 

Description:

Returns whether Organization Administrator is able to manage his
 organization configuration. This may have a high impact on general SUSE Manager performance.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.boolean]#boolean#  status - Returns the status org admin management setting
 



[#apidoc-org-listOrgs-391595516]
== Method: listOrgs 

Description:

Returns the list of organizations.




Parameters:

* [.string]#string#  sessionKey
 

Returns:

* [.array]#array# :
     * [.struct]#struct#  - organization info
   ** [.int]#int#  "id"
   ** [.string]#string#  "name"
   ** [.int]#int#  "active_users" - Number of active users in the organization.
   ** [.int]#int#  "systems" - Number of systems in the organization.
   ** [.int]#int#  "trusts" - Number of trusted organizations.
   ** [.int]#int#  "system_groups" - Number of system groups in the organization. (optional)
   ** [.int]#int#  "activation_keys" - Number of activation keys in the organization. (optional)
   ** [.int]#int#  "kickstart_profiles" - Number of kickstart profiles in the organization. (optional)
   ** [.int]#int#  "configuration_channels" - Number of configuration channels in the organization. (optional)
   ** [.boolean]#boolean#  "staging_content_enabled" - Is staging content enabled in organization. (optional)
  
    



[#apidoc-org-listUsers-524225829]
== Method: listUsers 

Description:

Returns the list of users in a given organization.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 

Returns:

* [.array]#array# :
     * [.struct]#struct#  - user
   ** [.string]#string#  "login"
   ** [.string]#string#  "login_uc"
   ** [.string]#string#  "name"
   ** [.string]#string#  "email"
   ** [.boolean]#boolean#  "is_org_admin"
  
    



[#apidoc-org-migrateSystems-52439501]
== Method: migrateSystems (Deprecated)

Description:

Transfer systems from one organization to another.  If executed by
 a SUSE Manager administrator, the systems will be transferred from their current
 organization to the organization specified by the toOrgId.  If executed by
 an organization administrator, the systems must exist in the same organization
 as that administrator and the systems will be transferred to the organization
 specified by the toOrgId. In any scenario, the origination and destination
 organizations must be defined in a trust.

 Note: This method is deprecated and will be removed in a future API version. Please use
 transferSystems instead.


Deprecated - being replaced by org.transferSystems(User loggedInUser, Integer toOrgId,
 List(Integer) sids)


Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  toOrgId - ID of the organization where the
 system(s) will be transferred to.
 
* [.array]#array# :
** [.int]#int#  - systemId
 

Returns:

* [.array]#array# :
** [.int]#int#  - serverIdTransferred
 



[#apidoc-org-setClmSyncPatchesConfig-1844179384]
== Method: setClmSyncPatchesConfig 

Description:

Sets the content lifecycle management patch synchronization config option.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.boolean]#boolean#  value - The config option value
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setContentStaging-430231018]
== Method: setContentStaging 

Description:

Set the status of content staging for the given organization.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.boolean]#boolean#  enable - Use true/false to enable/disable
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setErrataEmailNotifsForOrg-1932244125]
== Method: setErrataEmailNotifsForOrg 

Description:

Dis/enables errata e-mail notifications for the organization




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.boolean]#boolean#  enable - Use true/false to enable/disable
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setOrgConfigManagedByOrgAdmin-1660891176]
== Method: setOrgConfigManagedByOrgAdmin 

Description:

Sets whether Organization Administrator can manage his organization
 configuration. This may have a high impact on general SUSE Manager performance.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.boolean]#boolean#  enable - Use true/false to enable/disable
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setPolicyForScapFileUpload-616302301]
== Method: setPolicyForScapFileUpload 

Description:

Set the status of SCAP detailed result file upload settings
 for the given organization.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.struct]#struct#  - scap_upload_info
         ** [.boolean]#boolean#  "enabled" - Aggregation of detailed SCAP results is enabled.
         ** [.int]#int#  "size_limit" - Limit (in Bytes) for a single SCAP file upload.
      

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-setPolicyForScapResultDeletion-618120037]
== Method: setPolicyForScapResultDeletion 

Description:

Set the status of SCAP result deletion settins for the given
 organization.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.struct]#struct#  - scap_deletion_info
         ** [.boolean]#boolean#  "enabled" - Deletion of SCAP results is enabled
         ** [.int]#int#  "retention_period" - Period (in days) after which a scan can be deleted (if enabled).
      

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-org-transferSystems-1224302486]
== Method: transferSystems 

Description:

Transfer systems from one organization to another.  If executed by
 a SUSE Manager administrator, the systems will be transferred from their current
 organization to the organization specified by the toOrgId.  If executed by
 an organization administrator, the systems must exist in the same organization
 as that administrator and the systems will be transferred to the organization
 specified by the toOrgId. In any scenario, the origination and destination
 organizations must be defined in a trust.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  toOrgId - ID of the organization where the
 system(s) will be transferred to.
 
* [.array]#array# :
** [.int]#int#  - systemId
 

Returns:

* [.array]#array# :
** [.int]#int#  - serverIdTransferred
 



[#apidoc-org-updateName-8633259]
== Method: updateName 

Description:

Updates the name of an organization




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId
 
* [.string]#string#  name - Organization name. Must meet same
 criteria as in the web UI.
 

Returns:

* * [.struct]#struct#  - organization info
   ** [.int]#int#  "id"
   ** [.string]#string#  "name"
   ** [.int]#int#  "active_users" - Number of active users in the organization.
   ** [.int]#int#  "systems" - Number of systems in the organization.
   ** [.int]#int#  "trusts" - Number of trusted organizations.
   ** [.int]#int#  "system_groups" - Number of system groups in the organization. (optional)
   ** [.int]#int#  "activation_keys" - Number of activation keys in the organization. (optional)
   ** [.int]#int#  "kickstart_profiles" - Number of kickstart profiles in the organization. (optional)
   ** [.int]#int#  "configuration_channels" - Number of configuration channels in the organization. (optional)
   ** [.boolean]#boolean#  "staging_content_enabled" - Is staging content enabled in organization. (optional)
   
 


