[#apidoc-recurringaction]
= recurringaction


== Available methods

* <<apidoc-recurringaction-create-loggedInUser-actionProps,create>>
* <<apidoc-recurringaction-delete-loggedInUser-actionId,delete>>
* <<apidoc-recurringaction-listByEntity-loggedInUser-entityId-entityType,listByEntity>>
* <<apidoc-recurringaction-lookupById-loggedInUser-actionId,lookupById>>
* <<apidoc-recurringaction-update-loggedInUser-actionProps,update>>

== Description

Provides methods to handle recurring actions for minions, system groups and organizations.
 
 Deprecated - This namespace will be removed in a future API version. To work with recurring actions,
 please check out the newer 'recurring' namespace.

*Namespace*:

recurringaction


[#apidoc-recurringaction-create-loggedInUser-actionProps]
== Method: create (Deprecated)

HTTP `POST`

Description:

Create a new recurring highstate action.


Deprecated - This method will be removed in a future API version. To create recurring actions, please use either
 'recurring.highstate.create' or 'recurring.custom.create' instead.


Parameters:

* [.string]#string#  sessionKey
 
* [.struct]#struct#  actionProps
** [.string]#string#  "entity_type" - the type of the target entity. One of the following:
*** minion
*** group
*** org
** [.int]#int#  "entity_id" - the ID of the target entity
** [.string]#string#  "name" - the name of the action
** [.string]#string#  "cron_expr" - the execution frequency of the action
** [.boolean]#boolean#  "test" - whether the action should be executed in test mode (optional)
 

Returns:

* [.int]#int#  id - the ID of the recurring action
 



[#apidoc-recurringaction-delete-loggedInUser-actionId]
== Method: delete (Deprecated)

HTTP `POST`

Description:

Delete a recurring action with the given action ID.


Deprecated - This method will be removed in a future API version. To work with recurring actions, please check
 out the newer 'recurring' namespace.


Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  actionId - the action ID
 

Returns:

* [.int]#int#  id - the ID of the recurring action
 



[#apidoc-recurringaction-listByEntity-loggedInUser-entityId-entityType]
== Method: listByEntity (Deprecated)

HTTP `GET`

Description:

Return a list of recurring actions for a given entity.


Deprecated - This method will be removed in a future API version. To work with recurring actions, please check
 out the newer 'recurring' namespace.


Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  "entityType" - the type of the target entity. One of the following:
** MINION
** GROUP
** ORG
 
* [.int]#int#  entityId - the ID of the target entity
 

Returns:

* [.array]#array# :
          * [.struct]#struct#  recurring action information (some fields may be absent for some action types)
** [.int]#int#  "id"
** [.string]#string#  "name"
** [.int]#int#  "entity_id"
** [.string]#string#  "entity_type"
** [.string]#string#  "cron_expr"
** [.dateTime.iso8601]#dateTime.iso8601#  "created"
** [.string]#string#  "creator"
** [.boolean]#boolean#  "test"
** [.array]#string array#  "states" - the ordered list of states to be executed by a custom state action
** [.boolean]#boolean#  "active"
 
 



[#apidoc-recurringaction-lookupById-loggedInUser-actionId]
== Method: lookupById (Deprecated)

HTTP `GET`

Description:

Find a recurring action with the given action ID.


Deprecated - This method will be removed in a future API version. To work with recurring actions, please check
 out the newer 'recurring' namespace.


Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  actionId - the action ID
 

Returns:

* * [.struct]#struct#  recurring action information (some fields may be absent for some action types)
** [.int]#int#  "id"
** [.string]#string#  "name"
** [.int]#int#  "entity_id"
** [.string]#string#  "entity_type"
** [.string]#string#  "cron_expr"
** [.dateTime.iso8601]#dateTime.iso8601#  "created"
** [.string]#string#  "creator"
** [.boolean]#boolean#  "test"
** [.array]#string array#  "states" - the ordered list of states to be executed by a custom state action
** [.boolean]#boolean#  "active"
  
 



[#apidoc-recurringaction-update-loggedInUser-actionProps]
== Method: update (Deprecated)

HTTP `POST`

Description:

Update a recurring highstate action.


Deprecated - This method will be removed in a future API version. To update recurring actions, please use either
 'recurring.highstate.update' or 'recurring.custom.update' instead.


Parameters:

* [.string]#string#  sessionKey
 
* [.struct]#struct#  actionProps
** [.int]#int#  "id" - the ID of the action to update
** [.string]#string#  "name" - the name of the action (optional)
** [.string]#string#  "cron_expr" - the execution frequency of the action (optional)
** [.boolean]#boolean#  "test" - whether the action should be executed in test mode (optional)
** [.boolean]#boolean#  "active" - whether the action should be active (optional)
 

Returns:

* [.int]#int#  id - the ID of the recurring action
 


