[#apidoc-system_config]
= system.config


== Available methods

* <<apidoc-system_config-addChannels-635096154,addChannels>>
* <<apidoc-system_config-createOrUpdatePath-1389208765,createOrUpdatePath>>
* <<apidoc-system_config-createOrUpdateSymlink-1084946006,createOrUpdateSymlink>>
* <<apidoc-system_config-deleteFiles-377277500,deleteFiles>>
* <<apidoc-system_config-deployAll-690715138,deployAll>>
* <<apidoc-system_config-listChannels-1042555191,listChannels>>
* <<apidoc-system_config-listFiles-208144409,listFiles>>
* <<apidoc-system_config-lookupFileInfo-1511538598,lookupFileInfo>>
* <<apidoc-system_config-removeChannels-658399791,removeChannels>>
* <<apidoc-system_config-scheduleApplyConfigChannel-940364390,scheduleApplyConfigChannel>>
* <<apidoc-system_config-setChannels-1438120433,setChannels>>

== Description

Provides methods to access and modify many aspects of
 configuration channels and server association.
 basically system.config name space

*Namespace*:

system.config


[#apidoc-system_config-addChannels-635096154]
== Method: addChannels 

Description:

Given a list of servers and configuration channels,
 this method appends the configuration channels to either the top or
 the bottom (whichever you specify) of a system's subscribed
 configuration channels list. The ordering of the configuration channels
 provided in the add list is maintained while adding.
 If one of the configuration channels in the 'add' list
 has been previously subscribed by a server, the
 subscribed channel will be re-ranked to the appropriate place.




Parameters:

  * [.string]#string#  sessionKey
 
* [.array]#array# :
** [.int]#int#  - IDs of the systems to add the channels to.
 
* [.array]#array# :
** [.string]#string#  - List of configuration channel labels in the ranked order.
 
* [.boolean]#boolean#  addToTop
      
          * true - to prepend the given channels
          list to the top of the configuration channels list of a server
          * false - to append the given  channels
          list to the bottom of the configuration channels list of a server
      
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-system_config-createOrUpdatePath-1389208765]
== Method: createOrUpdatePath 

Description:

Create a new file (text or binary) or directory with the given path, or
 update an existing path on a server.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  serverId
 
* [.string]#string#  path - the configuration file/directory path
 
* [.boolean]#boolean#  isDir
      
          * True - if the path is a directory
          * False - if the path is a file
      
 
* [.struct]#struct#  - path info
      ** [.string]#string#  "contents" - Contents of the file (text or base64 encoded if binary)
                   ((only for non-directories)
      ** [.boolean]#boolean#  "contents_enc64" - Identifies base64 encoded content
                  (default: disabled, only for non-directories).
      ** [.string]#string#  "owner" - Owner of the file/directory.
      ** [.string]#string#  "group" - Group name of the file/directory.
      ** [.string]#string#  "permissions" - Octal file/directory permissions (eg: 644)
      ** [.string]#string#  "macro-start-delimiter" - Config file macro end delimiter. Use null or empty string
              to accept the default. (only for non-directories)
      ** [.string]#string#  "macro-end-delimiter" - Config file macro end delimiter. Use null or empty string
              to accept the default. (only for non-directories)
      ** [.string]#string#  "selinux_ctx" - SeLinux context (optional)
      ** [.int]#int#  "revision" - next revision number, auto increment for null
      ** [.boolean]#boolean#  "binary" - mark the binary content, if True,
      base64 encoded content is expected (only for non-directories)
   
* [.int]#int#  commitToLocal
      
          * 1 - to commit configuration files
              to the system's local override configuration channel
          * 0 - to commit configuration files
              to the system's sandbox configuration channel
      
 

Returns:

* * [.struct]#struct#  - Configuration Revision information
   ** [.string]#string#  "type"
              
                  ** file
                  ** directory
                  ** symlink
              
   ** [.string]#string#  "path" - File Path
   ** [.string]#string#  "target_path" - Symbolic link Target File Path.
                              Present for Symbolic links only.
   ** [.string]#string#  "channel" - Channel Name
   ** [.string]#string#  "contents" - File contents (base64 encoded according
                to the contents_enc64 attribute)
   ** [.boolean]#boolean#  "contents_enc64" -  Identifies base64 encoded content
   ** [.int]#int#  "revision" - File Revision
   ** [.dateTime.iso8601]#dateTime.iso8601#  "creation" - Creation Date
   ** [.dateTime.iso8601]#dateTime.iso8601#  "modified" - Last Modified Date
   ** [.string]#string#  "owner" - File Owner. Present for files or directories only.
   ** [.string]#string#  "group" - File Group. Present for files or directories only.
   ** [.int]#int#  "permissions" - File Permissions (Deprecated).
                                  Present for files or directories only.
   ** [.string]#string#  "permissions_mode" - File Permissions.
                                      Present for files or directories only.
   ** [.string]#string#  "selinux_ctx" - SELinux Context (optional).
   ** [.boolean]#boolean#  "binary" - true/false , Present for files only.
   ** [.string]#string#  "sha256" - File's sha256 signature. Present for files only.
   ** [.string]#string#  "macro-start-delimiter" - Macro start delimiter for a config file. Present for text files only.
   ** [.string]#string#  "macro-end-delimiter" - Macro end delimiter for a config file. Present for text files only.
   
 

Available since API version: 10.2


[#apidoc-system_config-createOrUpdateSymlink-1084946006]
== Method: createOrUpdateSymlink 

Description:

Create a new symbolic link with the given path, or
 update an existing path.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  serverId
 
* [.string]#string#  path - the configuration file/directory path
 
* [.struct]#struct#  - path info
      ** [.string]#string#  "target_path" - The target path for the symbolic link
      ** [.string]#string#  "selinux_ctx" - SELinux Security context (optional)
      ** [.int]#int#  "revision" - next revision number, auto increment for null
   
* [.int]#int#  commitToLocal
      
          * 1 - to commit configuration files
              to the system's local override configuration channel
          * 0 - to commit configuration files
              to the system's sandbox configuration channel
      
 

Returns:

* * [.struct]#struct#  - Configuration Revision information
   ** [.string]#string#  "type"
              
                  ** file
                  ** directory
                  ** symlink
              
   ** [.string]#string#  "path" - File Path
   ** [.string]#string#  "target_path" - Symbolic link Target File Path.
                              Present for Symbolic links only.
   ** [.string]#string#  "channel" - Channel Name
   ** [.string]#string#  "contents" - File contents (base64 encoded according
                to the contents_enc64 attribute)
   ** [.boolean]#boolean#  "contents_enc64" -  Identifies base64 encoded content
   ** [.int]#int#  "revision" - File Revision
   ** [.dateTime.iso8601]#dateTime.iso8601#  "creation" - Creation Date
   ** [.dateTime.iso8601]#dateTime.iso8601#  "modified" - Last Modified Date
   ** [.string]#string#  "owner" - File Owner. Present for files or directories only.
   ** [.string]#string#  "group" - File Group. Present for files or directories only.
   ** [.int]#int#  "permissions" - File Permissions (Deprecated).
                                  Present for files or directories only.
   ** [.string]#string#  "permissions_mode" - File Permissions.
                                      Present for files or directories only.
   ** [.string]#string#  "selinux_ctx" - SELinux Context (optional).
   ** [.boolean]#boolean#  "binary" - true/false , Present for files only.
   ** [.string]#string#  "sha256" - File's sha256 signature. Present for files only.
   ** [.string]#string#  "macro-start-delimiter" - Macro start delimiter for a config file. Present for text files only.
   ** [.string]#string#  "macro-end-delimiter" - Macro end delimiter for a config file. Present for text files only.
   
 

Available since API version: 10.2


[#apidoc-system_config-deleteFiles-377277500]
== Method: deleteFiles 

Description:

Removes file paths from a local or sandbox channel of a server.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  serverId
 
* [.array]#array# :
** [.string]#string#  - paths to remove.
 
* [.boolean]#boolean#  deleteFromLocal
      
          * True - to delete configuration file paths
              from the system's local override configuration channel
          * False - to delete configuration file paths
              from the system's sandbox configuration channel
      
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-system_config-deployAll-690715138]
== Method: deployAll 

Description:

Schedules a deploy action for all the configuration files
 on the given list of systems.




Parameters:

  * [.string]#string#  sessionKey
 
* [.array]#array# :
** [.int]#int#  - id of the systems to schedule configuration files deployment
 
* [.dateTime.iso8601]#dateTime.iso8601#  date - Earliest date for the deploy action.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-system_config-listChannels-1042555191]
== Method: listChannels 

Description:

List all global('Normal', 'State') configuration channels associated to a
              system in the order of their ranking.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  serverId
 

Returns:

* [.array]#array# :
  * [.struct]#struct#  - Configuration Channel information
   ** [.int]#int#  "id"
   ** [.int]#int#  "orgId"
   ** [.string]#string#  "label"
   ** [.string]#string#  "name"
   ** [.string]#string#  "description"
   ** [.struct]#struct#  "configChannelType"
   * [.struct]#struct#  - Configuration Channel Type information
   ** [.int]#int#  "id"
   ** [.string]#string#  "label"
   ** [.string]#string#  "name"
   ** [.int]#int#  "priority"
  
  
   



[#apidoc-system_config-listFiles-208144409]
== Method: listFiles 

Description:

Return the list of files in a given channel.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  serverId
 
* [.int]#int#  listLocal
      
          * 1 - to return configuration files
              in the system's local override configuration channel
          * 0 - to return configuration files
              in the system's sandbox configuration channel
      
 

Returns:

* [.array]#array# :
 * [.struct]#struct#  - Configuration File information
   ** [.string]#string#  "type"
              
                  ** file
                  ** directory
                  ** symlink
              
   ** [.string]#string#  "path" - File Path
   ** [.string]#string#  "channel_label" - the label of the  central configuration channel
      that has this file. Note this entry only shows up
      if the file has not been overridden by a central channel.
   ** [.struct]#struct#  "channel_type"
   * [.struct]#struct#  - Configuration Channel Type information
   ** [.int]#int#  "id"
   ** [.string]#string#  "label"
   ** [.string]#string#  "name"
   ** [.int]#int#  "priority"
  
   ** [.dateTime.iso8601]#dateTime.iso8601#  "last_modified" - Last Modified Date
  
  



[#apidoc-system_config-lookupFileInfo-1511538598]
== Method: lookupFileInfo 

Description:

Given a list of paths and a server, returns details about
 the latest revisions of the paths.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  serverId
 
* [.array]#array# :
** [.string]#string#  - paths to lookup on.
 
* [.int]#int#  searchLocal
      
          * 1 - to search configuration file paths
              in the system's local override configuration or
              systems subscribed central channels
          * 0 - to search configuration file paths
              in the system's sandbox configuration channel
      
 

Returns:

* [.array]#array# :
          * [.struct]#struct#  - Configuration Revision information
   ** [.string]#string#  "type"
              
                  ** file
                  ** directory
                  ** symlink
              
   ** [.string]#string#  "path" - File Path
   ** [.string]#string#  "target_path" - Symbolic link Target File Path.
                              Present for Symbolic links only.
   ** [.string]#string#  "channel" - Channel Name
   ** [.string]#string#  "contents" - File contents (base64 encoded according
                to the contents_enc64 attribute)
   ** [.boolean]#boolean#  "contents_enc64" -  Identifies base64 encoded content
   ** [.int]#int#  "revision" - File Revision
   ** [.dateTime.iso8601]#dateTime.iso8601#  "creation" - Creation Date
   ** [.dateTime.iso8601]#dateTime.iso8601#  "modified" - Last Modified Date
   ** [.string]#string#  "owner" - File Owner. Present for files or directories only.
   ** [.string]#string#  "group" - File Group. Present for files or directories only.
   ** [.int]#int#  "permissions" - File Permissions (Deprecated).
                                  Present for files or directories only.
   ** [.string]#string#  "permissions_mode" - File Permissions.
                                      Present for files or directories only.
   ** [.string]#string#  "selinux_ctx" - SELinux Context (optional).
   ** [.boolean]#boolean#  "binary" - true/false , Present for files only.
   ** [.string]#string#  "sha256" - File's sha256 signature. Present for files only.
   ** [.string]#string#  "macro-start-delimiter" - Macro start delimiter for a config file. Present for text files only.
   ** [.string]#string#  "macro-end-delimiter" - Macro end delimiter for a config file. Present for text files only.
  
       

Available since API version: 10.2


[#apidoc-system_config-removeChannels-658399791]
== Method: removeChannels 

Description:

Remove config channels from the given servers.




Parameters:

  * [.string]#string#  sessionKey
 
* [.array]#array# :
** [.int]#int#  - the IDs of the systems from which you
              would like to remove configuration channels..
 
* [.array]#array# :
** [.string]#string#  - List of configuration channel labels to remove.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-system_config-scheduleApplyConfigChannel-940364390]
== Method: scheduleApplyConfigChannel 

Description:

Schedule highstate application for a given system.




Parameters:

  * [.string]#string#  sessionKey
 
* [.int]#int#  serverId
 
* [.dateTime.iso8601]#dateTime.iso8601#  earliestOccurrence
 
* [.boolean]#boolean#  test - Run states in test-only mode
 

Returns:

* [.int]#int#  actionId
 



[#apidoc-system_config-setChannels-1438120433]
== Method: setChannels 

Description:

Replace the existing set of config channels on the given servers.
 Channels are ranked according to their order in the configChannelLabels
 array.




Parameters:

  * [.string]#string#  sessionKey
 
* [.array]#array# :
** [.int]#int#  - IDs of the systems to set the channels on.
 
* [.array]#array# :
** [.string]#string#  - List of configuration channel labels in the ranked order.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 


