[#apidoc-user_external]
= user.external


== Available methods

* <<apidoc-user_external-createExternalGroupToRoleMap-1942806465,createExternalGroupToRoleMap>>
* <<apidoc-user_external-createExternalGroupToSystemGroupMap-491457031,createExternalGroupToSystemGroupMap>>
* <<apidoc-user_external-deleteExternalGroupToRoleMap-1215109224,deleteExternalGroupToRoleMap>>
* <<apidoc-user_external-deleteExternalGroupToSystemGroupMap-2062929510,deleteExternalGroupToSystemGroupMap>>
* <<apidoc-user_external-getDefaultOrg-155333444,getDefaultOrg>>
* <<apidoc-user_external-getExternalGroupToRoleMap-416864887,getExternalGroupToRoleMap>>
* <<apidoc-user_external-getExternalGroupToSystemGroupMap-396926129,getExternalGroupToSystemGroupMap>>
* <<apidoc-user_external-getKeepTemporaryRoles-559872790,getKeepTemporaryRoles>>
* <<apidoc-user_external-getUseOrgUnit-446573627,getUseOrgUnit>>
* <<apidoc-user_external-listExternalGroupToRoleMaps-1565193331,listExternalGroupToRoleMaps>>
* <<apidoc-user_external-listExternalGroupToSystemGroupMaps-1059846157,listExternalGroupToSystemGroupMaps>>
* <<apidoc-user_external-setDefaultOrg-1603462635,setDefaultOrg>>
* <<apidoc-user_external-setExternalGroupRoles-1345177914,setExternalGroupRoles>>
* <<apidoc-user_external-setExternalGroupSystemGroups-1761528165,setExternalGroupSystemGroups>>
* <<apidoc-user_external-setKeepTemporaryRoles-1842676608,setKeepTemporaryRoles>>
* <<apidoc-user_external-setUseOrgUnit-389916964,setUseOrgUnit>>

== Description

If you are using IPA integration to allow authentication of users from
 an external IPA server (rare) the users will still need to be created in the #product()
 database. Methods in this namespace allow you to configure some specifics of how this
 happens, like what organization they are created in or what roles they will have.
 These options can also be set in the web admin interface.

*Namespace*:

user.external


[#apidoc-user_external-createExternalGroupToRoleMap-1942806465]
== Method: createExternalGroupToRoleMap

HTTP `POST`

Description:

Externally authenticated users may be members of external groups. You
 can use these groups to assign additional roles to the users when they log in.
 Can only be called by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name - Name of the external group. Must be
 unique.
 
* [.array]#string array#  roles - role - Can be any of:
 satellite_admin, org_admin (implies all other roles except for satellite_admin),
 channel_admin, config_admin, system_group_admin, or
 activation_key_admin.
 

Returns:

* * [.struct]#struct#  external group
** [.string]#string#  "name"
** [.array]#string array#  "roles" - role
  
 



[#apidoc-user_external-createExternalGroupToSystemGroupMap-491457031]
== Method: createExternalGroupToSystemGroupMap

HTTP `POST`

Description:

Externally authenticated users may be members of external groups. You
 can use these groups to give access to server groups to the users when they log in.
 Can only be called by an org_admin.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name - Name of the external group. Must be
 unique.
 
* [.array]#string array#  groupNames - the names of the server
 groups to grant access to.
 

Returns:

* * [.struct]#struct#  external group
** [.string]#string#  "name"
** [.array]#string array#  "groups" - roles
  
 



[#apidoc-user_external-deleteExternalGroupToRoleMap-1215109224]
== Method: deleteExternalGroupToRoleMap

HTTP `POST`

Description:

Delete the role map for an external group. Can only be called
 by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name - Name of the external group.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-user_external-deleteExternalGroupToSystemGroupMap-2062929510]
== Method: deleteExternalGroupToSystemGroupMap

HTTP `POST`

Description:

Delete the server group map for an external group. Can only be called
 by an org_admin.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name - Name of the external group.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-user_external-getDefaultOrg-155333444]
== Method: getDefaultOrg

HTTP `GET`

Description:

Get the default org that users should be added in if orgunit from
 IPA server isn't found or is disabled. Can only be called by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 

Returns:

* [.int]#int#  id - ID of the default organization. 0 if there is no default
 



[#apidoc-user_external-getExternalGroupToRoleMap-416864887]
== Method: getExternalGroupToRoleMap

HTTP `GET`

Description:

Get a representation of the role mapping for an external group.
 Can only be called by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name - Name of the external group.
 

Returns:

* * [.struct]#struct#  external group
** [.string]#string#  "name"
** [.array]#string array#  "roles" - role
  
 



[#apidoc-user_external-getExternalGroupToSystemGroupMap-396926129]
== Method: getExternalGroupToSystemGroupMap

HTTP `GET`

Description:

Get a representation of the server group mapping for an external
 group. Can only be called by an org_admin.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name - Name of the external group.
 

Returns:

* * [.struct]#struct#  external group
** [.string]#string#  "name"
** [.array]#string array#  "groups" - roles
  
 



[#apidoc-user_external-getKeepTemporaryRoles-559872790]
== Method: getKeepTemporaryRoles

HTTP `GET`

Description:

Get whether we should keeps roles assigned to users because of
 their IPA groups even after they log in through a non-IPA method. Can only be
 called by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 

Returns:

* [.boolean]#boolean#  keep - True if we should keep roles
 after users log in through non-IPA method, false otherwise
 



[#apidoc-user_external-getUseOrgUnit-446573627]
== Method: getUseOrgUnit

HTTP `GET`

Description:

Get whether we place users into the organization that corresponds
 to the "orgunit" set on the IPA server. The orgunit name must match exactly the
 #product() organization name. Can only be called by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 

Returns:

* [.boolean]#boolean#  use - True if we should use the IPA
 orgunit to determine which organization to create the user in, false otherwise
 



[#apidoc-user_external-listExternalGroupToRoleMaps-1565193331]
== Method: listExternalGroupToRoleMaps

HTTP `GET`

Description:

List role mappings for all known external groups. Can only be called
 by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 

Returns:

* [.array]#array# :
     * [.struct]#struct#  external group
** [.string]#string#  "name"
** [.array]#string array#  "roles" - role
 
 



[#apidoc-user_external-listExternalGroupToSystemGroupMaps-1059846157]
== Method: listExternalGroupToSystemGroupMaps

HTTP `GET`

Description:

List server group mappings for all known external groups. Can only be
 called by an org_admin.




Parameters:

* [.string]#string#  sessionKey
 

Returns:

* [.array]#array# :
     * [.struct]#struct#  external group
** [.string]#string#  "name"
** [.array]#string array#  "groups" - roles
 
 



[#apidoc-user_external-setDefaultOrg-1603462635]
== Method: setDefaultOrg

HTTP `POST`

Description:

Set the default org that users should be added in if orgunit from
 IPA server isn't found or is disabled. Can only be called by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 
* [.int]#int#  orgId - ID of the organization to set
 as the default org. 0 if there should not be a default organization.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-user_external-setExternalGroupRoles-1345177914]
== Method: setExternalGroupRoles

HTTP `POST`

Description:

Update the roles for an external group. Replace previously set roles
 with the ones passed in here. Can only be called by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name - Name of the external group.
 
* [.array]#string array#  roles - role - Can be any of:
 satellite_admin, org_admin (implies all other roles except for satellite_admin),
 channel_admin, config_admin, system_group_admin, or
 activation_key_admin.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-user_external-setExternalGroupSystemGroups-1761528165]
== Method: setExternalGroupSystemGroups

HTTP `POST`

Description:

Update the server groups for an external group. Replace previously set
 server groups with the ones passed in here. Can only be called by an org_admin.




Parameters:

* [.string]#string#  sessionKey
 
* [.string]#string#  name - Name of the external group.
 
* [.array]#string array#  groupNames - the names of the
 server groups to grant access to.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-user_external-setKeepTemporaryRoles-1842676608]
== Method: setKeepTemporaryRoles

HTTP `POST`

Description:

Set whether we should keeps roles assigned to users because of
 their IPA groups even after they log in through a non-IPA method. Can only be
 called by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 
* [.boolean]#boolean#  keepRoles - True if we should keep roles
 after users log in through non-IPA method, false otherwise.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 



[#apidoc-user_external-setUseOrgUnit-389916964]
== Method: setUseOrgUnit

HTTP `POST`

Description:

Set whether we place users into the organization that corresponds
 to the "orgunit" set on the IPA server. The orgunit name must match exactly the
 #product() organization name. Can only be called by a #product() Administrator.




Parameters:

* [.string]#string#  sessionKey
 
* [.boolean]#boolean#  useOrgUnit - true if we should use the IPA
 orgunit to determine which organization to create the user in, false otherwise.
 

Returns:

* [.int]#int#  - 1 on success, exception thrown otherwise.
 


