package generate

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// apiListEntryRe matches lines like: * <<channel.adoc#apidoc-channel>>
// The file ref and anchor are captured separately.
var apiListEntryRe = regexp.MustCompile(`^\*\s+<<([^#>]+)\.adoc#apidoc-([^>]+)>>`)

// APINav reads modules/api/pages/apilist.adoc (generated by the RPM build) and
// writes modules/api/nav-api-guide.adoc in the Antora xref format.
//
// The generated nav preserves the PDF preamble block at the top and prepends
// any fixed entries declared in cfg.Nav.Prepend (e.g. xref:faqs.adoc[FAQ]).
//
// Transformation: * <<channel.adoc#apidoc-channel>> → * xref:channel.adoc[channel]
func APINav(prepend []string, apiListPath, navOutPath string) error {
	// Read apilist.adoc
	f, err := os.Open(apiListPath)
	if err != nil {
		return fmt.Errorf("gen-nav: open %s: %w", apiListPath, err)
	}
	defer f.Close()

	var entries []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		m := apiListEntryRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		filename := m[1] // e.g. "channel"
		label := m[2]    // e.g. "channel" (after stripping "apidoc-")
		// Strip "apidoc-" prefix already handled by the regex group
		entries = append(entries, fmt.Sprintf("* xref:%s.adoc[%s]", filename, label))
	}
	if err := scanner.Err(); err != nil {
		return fmt.Errorf("gen-nav: read %s: %w", apiListPath, err)
	}

	if len(entries) == 0 {
		return fmt.Errorf("gen-nav: no entries found in %s", apiListPath)
	}

	// Build output
	if err := os.MkdirAll(filepath.Dir(navOutPath), 0o755); err != nil {
		return fmt.Errorf("gen-nav: mkdir: %w", err)
	}

	out, err := os.Create(navOutPath)
	if err != nil {
		return fmt.Errorf("gen-nav: create %s: %w", navOutPath, err)
	}
	defer out.Close()

	w := bufio.NewWriter(out)

	// PDF preamble block — kept as a literal header so gen-pdf-nav still works
	fmt.Fprintln(w, "// PDF API Documentation")
	fmt.Fprintln(w, "ifdef::backend-pdf[]")
	fmt.Fprintln(w, "= [.title]#{productname} API#: Version {productnumber}")
	fmt.Fprintln(w, "include::./branding/pdf/entities.adoc[]")
	fmt.Fprintln(w, ":toclevels: 3")
	fmt.Fprintln(w, ":doctype: book")
	fmt.Fprintln(w)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "endif::[]")
	fmt.Fprintln(w)

	// Fixed prepend entries (e.g. faqs.adoc[FAQ])
	for _, line := range prepend {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "* ") {
			line = "* " + line
		}
		fmt.Fprintln(w, line)
	}

	// Generated entries from apilist.adoc
	for _, entry := range entries {
		fmt.Fprintln(w, entry)
	}

	return w.Flush()
}
