package generate

// siteYMLTemplate is the Go text/template for per-output site.yml files.
const siteYMLTemplate = `# Generated by docbuild — do not edit by hand.
# Source: config.yml output: {{.Output}} lang: {{.Lang.Code}}
content:
  sources:
    - url: {{.RepoRoot}}
      start_path: {{.StartPath}}
      branches:
        - HEAD
output:
  dir: {{.OutputDir}}
runtime:
  cache_dir: {{.RepoRoot}}/.cache/antora
site:
  title: {{.Out.Site.Title}}
  url: {{.SiteURL}}
  start_page: {{.Out.Site.StartPage}}
antora:
  extensions:
{{- range .Cfg.Antora.Extensions}}
  - '{{.}}'
{{- end}}
asciidoc:
{{- if .Cfg.AsciidocExtensions}}
  extensions:
{{- range .Cfg.AsciidocExtensions}}
  - '{{.}}'
{{- end}}
{{- end}}
  attributes:
    page-lang: {{.Lang.Code}}
{{- range $k, $v := .Cfg.Asciidoc}}
    {{$k}}: '{{$v}}'
{{- end}}
{{- range $k, $v := .P.Asciidoc.Attributes}}
    {{$k}}: '{{$v}}'
{{- end}}
ui:
  bundle:
    url: {{.BundleURL}}
    snapshot: true
{{- if .SupplementalFiles}}
  supplemental_files: {{.SupplementalFiles}}
{{- end}}
`

// antoraYMLTemplate is the Go text/template for antora.yml.
const antoraYMLTemplate = `# Generated by docbuild — do not edit by hand.
# Source: config.yml product: {{.Product}} lang: {{.Lang.Code}}
name: {{.P.Antora.Name}}
title: {{.P.Antora.Title}}
version: ~
start_page: ROOT:index.adoc
nav:
  - {{.ContentDir}}/ROOT/nav.adoc
{{- range .P.Sections}}
  - {{$.ContentDir}}/{{.}}/nav-{{.}}-guide.adoc
{{- end}}
`

// entitiesTemplate is the Go text/template for branding/pdf/entities.adoc.
const entitiesTemplate = `// Generated by docbuild — do not edit by hand.
// Source: config.yml product: {{.Product}} lang: {{.Lang.Code}}
// Product attributes
{{- range $k, $v := .P.Asciidoc.Attributes}}
:{{$k}}: {{$v}}
{{- end}}
// Shared attributes
{{- range $k, $v := .Cfg.Asciidoc}}
:{{$k}}: {{$v}}
{{- end}}
// Page-lang
:lang: {{.Lang.Code}}
{{.LocaleAttrs}}
`
